[settings]
disable_backends = ["asdf"] # cannot be updated by Renovate

[tools]
"aqua:astral-sh/uv" = "latest"
node = "latest"
"pipx:cruft" = "latest"
pnpm = "latest"
python = "latest"

[tasks]
install = "pnpm install"
dev = "pnpm run dev"
build = "pnpm run build"
preview = "pnpm run preview"
astro = "pnpm run astro"
lint = "pnpm run lint"
format = "pnpm run format"
typecheck = "pnpm run typecheck"

[tasks."template:update"]
description = "Update project with the latest changes from the template"
run = "cruft update"

[tasks."template:restore"]
description = "Restore template-managed files"
run = "cruft diff | git apply"
